= `vapic`
:toc!:

Versioned API Cache

== Installation

[source,bash]
----
npm install vapic --save
----

== Usage

=== `.set()`

Stores the value in the cache, against the current version.

[source,javascript]
----
const vapic = require('vapic');

vapic.set({
	url: '/foo',
	value: 'bar'),
	maxVersions: 3, // <1>
	redisClient: require('redis').createClient(),
}, (err, result) => { /* ... */ });
----
<1> If `maxVersions` is set, `cullOld()` is automatically called.

Options:

url:: Used to construct the cache key
value:: The value to store in the cache
maxVersions:: The maximum number of cached versions to store;
	when set `.cullOld()` is called.
versionMatchType:: How to determine which version to match. +
  When `exact` (the default), only an exact version match with the current version will be returned. +
	When `skipWhenSameAsLatest`, does not insert a new version if the value of the most recent version
	is the same as the new one you are inserting;
	use when multiple version are likely to contain the same value.

=== `.cullOld()`

Deletes older versions that have been cached.
The versions to keep/ remove are determined using `semver`.

[source,javascript]
----
const vapic = require('vapic');

vapic.cullOld({
	url: '/foo',
	maxVersions: 3,
	redisClient: require('redis').createClient(),
}, (err, result) => { /* ... */ });
----

Options:

Same as `.set()`.

=== `express` middleware

[source,javascript]
----
const vapic = require('vapic');
const express = require('express');

const vapicOptions = {
	permittedAge: 3600, // one hour
	cacheVersion: require('package.json').version,
	redisClient: require('redis').createClient(),
};

const router = express.Router();
router.get('/foo', vapic.expressMiddleware(vapicOptions), (req, res) => {
  if (req.vapicError) {
		res.status(404).json({
			message: 'Data unavailable',
		});
		return;
	} else {
  	const data = JSON.parse(req.vapicResult);
  	res.json(data);
  	return;
  }
});

module.exports = router;
----

Options:

prefix:: Prefix for the cache key.
  Defaults to `vapic:/`
cacheVersion:: Cached version to use.
  Defaults to the version number of the current module,
	or `process.env.npm_package_version`
versionMatchType:: How to determine which version to match. +
  When `exact` (the default), only an exact version match with the current version will be returned. +
	When `latestUpToCurrent`, the latest version that is less than or equal to the current version will be returned. +
	Intended for use in conjunction with `.set()` where `versionMatchType=skipWhenSameAsLatest`
permittedAge:: The number of seconds the `Cache-Control` header in the response
  should set its `max-age` to.
  Defaults to `60` (One minute).
logger:: An object that has an `error` function.
  Defaults to `console`
redisClient:: A Redis client instance.
  Defaults to `require('redis').createClient()`.

== Development

If you would like to contribute,
fork the git repo,
and create a branch off the *develop* branch,
and submit your pull request when you are done.

This repo uses the *git flow* branching strategy.

To run tests:

[source,bash]
----
npm run test
----

== Author

http://bguiz.com[Brendan Graetz^]

== Licence

GPL-3.0
